Python 2.7 Titan:
  script:
  - py_version=2.7
  - EXTRA_INSTALL="numpy mako"
  - export PYCUDA_DEFAULT_NVCC_FLAGS="-ccbin g++-7"
  - echo "CUDADRV_LIB_DIR = ['/usr/lib/x86_64-linux-gnu/nvidia/current']" > siteconf.py
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - nvidia-titan-x
  except:
  - tags

Python 2.7 K40:
  script:
  - py_version=2.7
  - EXTRA_INSTALL="numpy mako"
  - export PYCUDA_DEFAULT_NVCC_FLAGS="-ccbin g++-7"
  - echo "CUDADRV_LIB_DIR = ['/usr/lib/x86_64-linux-gnu/nvidia/current']" > siteconf.py
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - nvidia-k40
  except:
  - tags

Python 3 Titan X:
  script:
  - py_version=3
  - EXTRA_INSTALL="numpy mako"
  - export PYCUDA_DEFAULT_NVCC_FLAGS="-ccbin g++-7"
  - echo "CUDADRV_LIB_DIR = ['/usr/lib/x86_64-linux-gnu/nvidia/current']" > siteconf.py
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  - nvidia-titan-x
  except:
  - tags

Python 3 Titan V:
  script:
  - py_version=3
  - EXTRA_INSTALL="numpy mako"
  - export PYCUDA_DEFAULT_NVCC_FLAGS="-ccbin g++-7"
  - echo "CUDADRV_LIB_DIR = ['/usr/lib/x86_64-linux-gnu/nvidia/current']" > siteconf.py
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  - nvidia-titan-v
  except:
  - tags

Python 3 K40:
  script:
  - py_version=3
  - EXTRA_INSTALL="numpy mako"
  - export PYCUDA_DEFAULT_NVCC_FLAGS="-ccbin g++-7"
  - echo "CUDADRV_LIB_DIR = ['/usr/lib/x86_64-linux-gnu/nvidia/current']" > siteconf.py
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  - nvidia-k40
  except:
  - tags

Documentation:
  script:
  - EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3
  - nvidia-titan-x
  only:
  - master
